### ISSUE TITLE
New annotation mechanism

### ISSUE THREAD

**Issue by MaksSieve** [TinkoffCreditSystems/gatling-picatinny#6]
Gatling 3.5.0 will deprecate after and before instructions for Simulaion.
They recomend to use sequential model. 

Need to create annotation step for injection DSL.

![image](https://user-images.githubusercontent.com/9395027/85514918-3c3ddb80-b605-11ea-986e-f3a87ebe0095.png)

**Comment by chepk** [comment]
Canceled:
https://github.com/gatling/gatling/issues/3892
https://github.com/gatling/gatling/commit/e88fc6aadc63664c32578ddde18aafba067d0976
